### ISSUE TITLE
Webhook question

### ISSUE THREAD

**Issue by thisisbenwoo** [meisnate12/Plex-Meta-Manager-Configs#112]
Hello,

I hope this question isn't too far outside the proper protocols. But I'm brand new to webhooks, and I'm trying to use telegram as a notification system.

So far I have:
```
webhooks:                                       # Can be individually specified per library as well
  error: https://api.telegram.org/bot[botid]/sendMessage?chat_id=[id]&
```
but I don't know what to put after the last & to put the message in there.

Thank you for allowing me to ask this question. 

b

**Comment by mtucker502** [comment]
You should probably ask this question in https://github.com/meisnate12/Plex-Meta-Manager

**Comment by cpt-kuesel** [comment]
Closing this issue as support for PMM is offered at https://github.com/meisnate12/Plex-Meta-Manager or in the PMM Discord https://discord.gg/NfH6mGFuAB
