### ISSUE TITLE
While trying to build a playlist sync_to_users is read as being empty but it's not

### ISSUE THREAD

**Issue by bulls23nt** [meisnate12/Plex-Meta-Manager-Configs#221]
Hi, so I'm trying to build a playlist that should only be created in my Kids user and mine, but every time I run it I get this on the log:

`=================================== Validating Bluey Attributes ====================================|
|                                                                                                    |
| Validating Method: libraries                                                                       |
| Value: TV Shows                                                                                    |
|                                                                                                    |
| Validating Method: sync_to_users                                                                   |
| Playlist Error: sync_to_users attribute is blank defaulting to playlist_sync_to_user: None         |
|                                                                                                    |
| Validating Method: sync_mode                                                                       |
| Value: sync                                                                                        |
|                                                                                                    |
| Validating Method: plex_search                                                                     |
| Value: ordereddict([('type', 'shows'), ('all', ordereddict([('title', 'Bluey')]))])                |
|                                                                                                    |
| Validating Method: summary                                                                         |
| Value: Auto Playlist                                                                               |
|                                                                                                    |
| Validation Successful`

The list gets created but initially it was creating it in all of my users until I set it globally to none, now it only creates it in my user. Here is what I'm using to define the playlist:

`  Bluey:
   sync_to_users: User1, User2
   sync_mode: sync
   libraries: TV Shows
   plex_search:
       type: shows
       all:
         title: "Bluey"
   summary: Auto Playlist`

I'm attaching some screenshot because the formatting for the playlist looks weird in the preview. 

For the user I have tried the name of the users as well but no matter what I write in there it says it's blank when I run it.
![playlist](https://user-images.githubusercontent.com/43219183/163897934-616d57cb-dad8-4ebc-98dd-f88b9212932b.jpg)
![screenshot from console](https://user-images.githubusercontent.com/43219183/163897964-5740696f-a160-4e1d-a871-64efb4d7a4cf.jpg)

**Comment by LampshadeTricky** [comment]
I'm having a similar issue, Per the documentation, leaving the sync_to_users blank should add a playlist to my the owner's playlist but instead it defaults to the config version.

**Comment by meisnate12** [comment]
this should be fixed in 1.17.0
