### ISSUE TITLE
ICHIMOKU overlay missing

### ISSUE THREAD

**Issue by nicolasrata** [meisnate12/Plex-Meta-Manager-Configs#296]
Hi, thanks a lot for all the awesome work we can find here !
@ICHlMOKU, it seems that the 4K-HDR-DolbyDigitalPlus overlay is missing.
Thank you if you find the time to add it

**Comment by ICHlMOKU** [comment]
@nicolasrata 
https://imgur.com/OZMg46c

**Comment by nicolasrata** [comment]
Nice !!!
Thanks a lot
