### ISSUE TITLE
[Bug]: PMM/show/network.yml doesn't have Netflix

### ISSUE THREAD

**Issue by karan** [meisnate12/Plex-Meta-Manager-Configs#395]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/PMM/show/network.yml

### Version Number

1.17.2

### What branch are you on?

master

### Describe the Bug

As in the title - Netflix is not present in `PMM/show/network.yml` but many other networks/studios are.

**Comment by YozoraXCII** [comment]
This is covered under PMM/streaming
