### ISSUE TITLE
Add SHOWTIME Original Series Dynamic Network Collections 

### ISSUE THREAD

**Issue by I-PlayBack** [meisnate12/Plex-Meta-Manager-Configs#407]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/PMM/show/network.yml

### Version Number

1.17.1

### What branch are you on?

master

### Describe the Bug

Add SHOWTIME Original Series & TV Shows to network.yml, sorry if this is the wrong place

**Comment by I-PlayBack** [comment]
Could also add STARZ

**Comment by YozoraXCII** [comment]
> Could also add STARZ

Apologies for the delayed response, I have added both networks and the relative images will be uploaded soon.
