### ISSUE TITLE
[Bug]: seasonal.yml

### ISSUE THREAD

**Issue by laryan61** [meisnate12/Plex-Meta-Manager-Configs#448]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/PMM/movie/seasonal.yml

### Version Number

1.17.3

### What branch are you on?

develop

### Describe the Bug

I'm calling seasonal.yml from my PMM installation. In my logs I see the following warning. Looks like a minor adjustment. I don't receive the warning with the other holidays.

[WARNING]  | Config Warning: Running collection_name as name
[DEBUG]    | Template Holiday
[DEBUG]    | Call: ordereddict([('name', 'Holiday'), ('season', 'thanksgiving'), ('schedule_thanksgiving', 'range(11/01-11/30)')])

I can see that you've constructed the Thanksgiving collection slightly different than the other collections.

Thanksgiving:
    collection_name: Thanksgiving
    template:
      - name: Holiday
vs.
 Independence Day:
    template:
      - name: Holiday
      -

**Comment by meisnate12** [comment]
this should be fixed
