### ISSUE TITLE
[Bug]: Genre shows no Cover for German configured Plex

### ISSUE THREAD

**Issue by poiy23** [meisnate12/Plex-Meta-Manager-Configs#498]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/tree/master/PMM

### Version Number

current

### What branch are you on?

master

### Describe the Bug

The Plex Genres are in German so PPM does not find the genre covers, beacause it searches a JPG with a german title whitch doesnt exists.

**Comment by cpt-kuesel** [comment]
the default files have been moved into the main repository with the recent release of PMM 1.18.0.
the files in this configs repo are stale and will probably removed in the future.
if you see this behaviour using `- pmm: ratings` with 1.18.0 open your issue over at the main repo.
