### ISSUE TITLE
[Bug]: ratings.yml - two ratings (top/center) - stacking ratings 

### ISSUE THREAD

**Issue by CaptainPimpJr** [meisnate12/Plex-Meta-Manager-Configs#524]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/PMM/overlays/ratings.yml

### Version Number

1.18

### What branch are you on?

master

### Describe the Bug

selecting just two ratings for overlay vertical_position: top, horizontal_position: center, alignment: horizontal leads to stacking ratings / images:
log:
`Conditional: rating1_horizontal_offset
Condition 1 Failed: rating_alignment "horizontal" is not "vertical"
Condition 2 Failed: rating2 "audience" is not "none"
Condition 3 Failed: rating2 "audience" is not "none" 
Conditional Variable: rating1_horizontal_offset is "-<<ch2_offset>>" `

and

`Conditional: rating2_horizontal_offset
Condition 1 Failed: rating_alignment "horizontal" is not "vertical"
Condition 2 Failed: rating1 "critic" is not "none" 
Condition 3 Failed: rating1 "critic" is not "none" 
Conditional Variable: rating2_horizontal_offset is "-<<ch2_offset>>"`

line 281 needs to end with:
` value: +<<ch2_offset>>` or ` value: <<ch2_offset>>`
instead of:
` value: -<<ch2_offset>>`

**Comment by CaptainPimpJr** [comment]
sorry might be important:
overlay_level: episode

<img width="109" alt="Bildschirmfoto 2022-11-17 um 21 56 19" src="https://user-images.githubusercontent.com/80001972/202558133-894ce21b-2d9c-456c-9ce2-f64ac331b561.png">

**Comment by cpt-kuesel** [comment]
the default files have been moved into the main repository with the recent release of PMM 1.18.0.
the files in this configs repo are stale and will probably removed in the future.
if you see this behaviour using `- pmm: ratings` with 1.18.0 open your issue over at the main repo.

**Comment by CaptainPimpJr** [comment]
will do - behaviour was documented from 1.18 using `-pmm: ratings `
my bad thought this is the right place to document.
