### ISSUE TITLE
[Bug]: Additions to Marvel Collections Request

### ISSUE THREAD

**Issue by ravensorb** [meisnate12/Plex-Meta-Manager-Configs#544]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/Frexe/Movies/Collections/Marvel%20Cinematic%20Universe.yml

### Version Number

1.18.3

### What branch are you on?

master

### Describe the Bug

Would it be possible to add a collection to group all of the Marvel Universe movies together and also support separators.

**Comment by cpt-kuesel** [comment]
you linked to a file of user @MasterFrexe 
if you ask them nicely they might indulge you and add stuff to the linked file.
separators are a pmm default thing, highly unlikely they will recreate those for you, i think you would need to do those yourself @ravensorb .

**Comment by MasterFrexe** [comment]
I don't understand the question there is already a collection whit all the Marvel movies?.

 "Marvel Cinematic Universe"

Feel free to send a message on discord and many we can work somthing out.

**Comment by ravensorb** [comment]
This is probably my bad as I am in the learning phase :)

I love the collection you have setup for Marvel Universe however I noticed that there doesn't seem to be a way to have it create a seperator and it doesn't create a "master" collection that includes all of the Marvel Universe into a single collection (maybe this is just my lack of knowing how to do some things yet?)
