### ISSUE TITLE
[Bug]: Draper: Anime: Seasons: We alrady have 2023

### ISSUE THREAD

**Issue by kiam001** [meisnate12/Plex-Meta-Manager-Configs#551]
### Link to File

https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Configs/master/Draper/Anime/Seasons.yml

### Version Number

1.18.3

### What branch are you on?

master

### Describe the Bug

Seasons Only to 2022 the 2023 line missing

**Comment by cpt-kuesel** [comment]
this is a file by community member @Drapersniper 

if you ask them nicely they might update their file @kiam001

**Comment by kiam001** [comment]
Nice thx for fixing it.
