### ISSUE TITLE
[Bug]: space_chef%20/

### ISSUE THREAD

**Issue by planetrocky** [meisnate12/Plex-Meta-Manager-Configs#639]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/tree/master/space_chef%20

### Version Number

ca8af7841b23f9e96c270b36913fa17ef26dfffd

### What branch are you on?

master

### Describe the Bug

Is it deliberate to have a the folder name "space_chef " with a trailing 0x20 (space character)?  This creates problems checking out on Windows:

Windows Shell won't allow trailing spaces, see here:

https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/file-folder-name-whitespace-characters

``` sh
$ git checkout
error: invalid path 'space_chef /Example Posters with Overlays/Breaking Bad.png'
error: invalid path 'space_chef /Example Posters with Overlays/Cosmos.png'
error: invalid path 'space_chef /Example Posters with Overlays/IMAX - Hidden Universe.png'
error: invalid path 'space_chef /Example Posters with Overlays/Oppenheimer.png'
error: invalid path 'space_chef /Example Posters with Overlays/The Matrix.png'
error: invalid path 'space_chef /Example Posters with Overlays/The Office.png'
error: invalid path 'space_chef /Example Posters with Overlays/The Return of the King [Extended].png'
error: invalid path 'space_chef /Example Posters with Overlays/The Shawshank Redemption.png'
error: invalid path 'space_chef /Example Posters with Overlays/Westworld.png'
error: invalid path 'space_chef /README.md'
```

**Comment by msorelle** [comment]
Tagging @nichols89ben since it was their changes that got merged that caused this.

**Comment by nichols89ben** [comment]
> Tagging @nichols89ben since it was their changes that got merged that caused this.

Edited!

**Comment by cpt-kuesel** [comment]
thanks, merged!

**Comment by planetrocky** [comment]
@msorelle came here and was about to say the same :)

This issue needs opening again please
